### ISSUE TITLE
Allow particles other than electrons to be traced

### ISSUE THREAD

**Issue by leon-vv** [leon-vv/Traceon#11]
## Problem statement

Currently, only electrons can be traced. Some people would want to trace ions as well.

## Proposed solution

Add two keywords to the `Tracer.__call__` function, allowing people to pass in the charge and mass of the particle that is to be traced. By default these keyword arguments are set to the charge and mass of an electron.

## How to test

Ensure that the trajectories for a particle which has 2x the mass, but also 2x the carge, stays equal.
Ensure that the trajectory of a massive particle is equal to that of an electron, if the voltages on the electrodes are multiplied by **minus** the ratio of their masses

**Comment by leon-vv** [comment]
Moving to v0.3 as I think first users will trace mainly with electrons

**Comment by jobdewitte** [comment]
Solved in #140.
