### ISSUE TITLE
Change color keyword arguments in plot_mesh function to take mesh instead of meshname as key

### ISSUE THREAD

**Issue by jobdewitte** [leon-vv/Traceon#111]
Right now the mesh name is taken as the key for the keyword argument in the plotting.plot_mesh() function. This somewhat restricts the naming (i.e, spaces can't be part of the mesh name if one wants to assign a color). Instead, the mesh variable should be used as key and the name merely for legend settings.

**Comment by leon-vv** [comment]
I don't fully understand the alternative that you propose. How would it be possible to take mesh as key?
